export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


export const SET_LOCATION = 'SET_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const SELECT_LOCATION = 'SELECT_LOCATION';

export const LOAD_WEATHER = 'LOAD_WEATHER';
export const LOAD_WEATHER_FAILED = 'LOAD_WEATHER_FAILED'