export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


export const SET_LOCATION = 'SET_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const SELECT_LOCATION = 'SELECT_LOCATION';

export const ADD_LOCATION = 'ADD_LOCATION';
export const STOP_ADDING_LOCATION = 'STOP_ADDING_LOCATION';
export const CREATE_LOCATION = 'CREATE_LOCATION';

export const WEATHER_LOADED = 'WEATHER_LOADED';
export const WEATHER_FAILED = 'WEATHER_FAILED';

export const FORECAST_LOADED = 'FORECAST_LOADED';
